### PR TITLE
Deprecate silent interpolation errors in multiline comments

### LINKED ISSUE #358: Deprecate non-standard support for broken interpolation in comments
Sass loud comments support interpolation. When implementing that to fix #38 in 1.0.5, a no-standard fallback was kept, rendering the comment source as is in case of error during the evaluation.
this non-standard behavior should be deprecated (reporting a Sass warning) so that we can then remove support for it.

### PR DESCRIPTION
**Pull request by stof**
Closes #358

I also submitted https://github.com/sass/sass-spec/pull/1644 to cover that case in sass-spec (which we will need to skip until the 2.0.0 release as sass-spec expects an error, not a deprecation warning while ignoring the error).

### CODE REVIEW

File: src/Parser.php [hunk 1]
```diff
@@ -1580,7 +1592,14 @@ protected function whitespace()
                 } else {
                     $comment[] = $c;
                     $staticComment = substr($this->buffer, $startCommentCount, $endCommentCount - $startCommentCount);
-                    $this->appendComment([Type::T_COMMENT, $staticComment, [Type::T_STRING, '', $comment]]);
+                    $commentStatement = [Type::T_COMMENT, $staticComment, [Type::T_STRING, '', $comment]];
+
+                    list($line, $column) = $this->getSourcePosition($startCommentCount);
+                    $commentStatement[self::SOURCE_LINE] = $line;
+                    $commentStatement[self::SOURCE_COLUMN] = $column;
+                    $commentStatement[self::SOURCE_INDEX] = $this->sourceIndex;
```
Comment (stof) [inline src/Parser.php:1600]: This ensure that errors happening in comments can be associated to the right position in the source file. I'm doing that only for cases that contain an interpolation (static comments are in the other branch of the conditions) as static comments won't need it (there is nothing that can trigger an error in them).
